version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    environment:
      POSTGRES_PASSWORD: admin
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:admin@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasura_admin
  adminer:
    image: adminer
    depends_on:
    - "postgres"
    restart: always
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
    - 8082:8080    
volumes:
  db_data:

